name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: ${{ matrix.lua }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua:
          - luajit
          - lua52
          - lua53
          - lua54
          - lua55
    steps:
      - name: Check out source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Run tests
        run: nix develop ".#${{ matrix.lua }}" -c busted
        env:
          LUA_PATH: ./src/?.lua;./src/?/init.lua;;

  rockspec:
    name: Validate rockspec
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Validate rockspec
        run: make lint
